INSERT INTO courses (name, teacher) VALUES ('Química', 'Profesor F');
INSERT INTO courses (name, teacher) VALUES ('Geografía', 'Profesor G');
INSERT INTO courses (name, teacher) VALUES ('Filosofía', 'Profesor H');
INSERT INTO courses (name, teacher) VALUES ('Arte', 'Profesor I');
INSERT INTO courses (name, teacher) VALUES ('Música', 'Profesor J');
INSERT INTO courses (name, teacher) VALUES ('Educación Física', 'Profesor K');
INSERT INTO courses (name, teacher) VALUES ('Programación', 'Profesor L');
INSERT INTO courses (name, teacher) VALUES ('Robótica', 'Profesor M');
INSERT INTO courses (name, teacher) VALUES ('Economía', 'Profesor N');
INSERT INTO courses (name, teacher) VALUES ('Psicología', 'Profesor O');
INSERT INTO courses (name, teacher) VALUES ('Sociología', 'Profesor P');
INSERT INTO courses (name, teacher) VALUES ('Astronomía', 'Profesor Q');
INSERT INTO courses (name, teacher) VALUES ('Cálculo', 'Profesor R');
INSERT INTO courses (name, teacher) VALUES ('Estadística', 'Profesor S');
INSERT INTO courses (name, teacher) VALUES ('Inglés', 'Profesor T');
INSERT INTO courses (name, teacher) VALUES ('Francés', 'Profesor U');
INSERT INTO courses (name, teacher) VALUES ('Alemán', 'Profesor V');
INSERT INTO courses (name, teacher) VALUES ('Teatro', 'Profesor W');
INSERT INTO courses (name, teacher) VALUES ('Diseño Gráfico', 'Profesor X');
INSERT INTO courses (name, teacher) VALUES ('Redacción', 'Profesor Y');
INSERT INTO courses (name, teacher) VALUES ('Matematicas', 'Profesor A');
INSERT INTO courses (name, teacher) VALUES ('Física', 'Profesor B');
INSERT INTO courses (name, teacher) VALUES ('Historia', 'Profesor C');
INSERT INTO courses (name, teacher) VALUES ('Literatura', 'Profesor D');
INSERT INTO courses (name, teacher) VALUES ('Biología', 'Profesor E');